trigger:
- XYZBank

pool:
  vmImage: 'windows-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'
    addToPath: true

- script: |
    python -m venv env
    source env/bin/activate
    pip install pytest
    pip install selenium
    pip install webdriver_manager
    pip install allure-pytest
    pip install faker
    pip install xlrd
    pytest Tests/
  workingDirectory: $(System.DefaultWorkingDirectory)
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    # PathToPublish: './TestResults/'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
    testRunTitle: 'Script results'