trigger:
- XYZBank

pool:
  vmImage: 'windows-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'
    addToPath: true

- script: |
    pytest Tests/
  workingDirectory: $(System.DefaultWorkingDirectory)

- script: |
    filename: 'run_tests.bat'
  workingDirectory: $(System.DefaultWorkingDirectory)

- script: |
    title: 'pytest scripts'
    testroot: '$(System.DefaultWorkingDirectory)'
    patterns: '.py'
    packages: 'Tests/'
    resultfile: 'pytest.html'
    pylint: true
    pytest Tests/
  workingDirectory: $(System.DefaultWorkingDirectory)