trigger:
- XYZBank

pool:
  vmImage: windows-latest

steps:

- task: BatchScript@1
  inputs:
    filename: 'run_tests.bat'
    arguments: ''
  displayName: 'Run tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: '**/pytest.html'
    testRunTitle: 'Test Run'