trigger:
- XYZBank

pool:
  vmImage: 'windows-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'
    addToPath: true

- script: |
    python -m venv env
    source env/bin/activate
    pip install pytest
    pip install selenium
    pip install webdriver_manager
    pip install allure-pytest
    pip install faker
    pip install xlrd
    pytest Tests/
  workingDirectory: $(System.DefaultWorkingDirectory)

- task: PublishTestResults@2
  inputs:
    testRunner: XUnit
    testResultsFiles: '**/test_results.html'
    testRunTitle: 'Test Results'