trigger:
- XYZBank

pool:
  vmImage: windows-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: printAllVariables@1
  displayName: 'Print all variables'

- task: BatchScript@1
  inputs:
    filename: 'run_tests.bat'
    arguments: ''
  displayName: 'Run tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: '**/pytest.xml'
    testRunTitle: 'Test Run'