trigger:
- XYZBank

pool:
  vmImage: 'windows-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'
    addToPath: true
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'pytest Tests/'

- script: |
    filename: 'run_tests.bat'
  workingDirectory: '$(System.DefaultWorkingDirectory)'
 
- script: |
    filename: 'run_tests.bat'
    workingFolder: 'XyzAutomation'

- script: |
    title: 'pytest scripts'
    testroot: '$(System.DefaultWorkingDirectory)'
    patterns: '.py'
    packages: 'Tests/'
    resultfile: 'pytest.html'
    pylint: true
    pytest Tests/
  workingDirectory: $(System.DefaultWorkingDirectory)