trigger:
- XYZBank

pool:
  vmImage: 'windows-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'
    addToPath: true

- script: |
    python -m venv env
    source env/bin/activate
    pip install pytest
    pip install selenium
    pip install webdriver_manager
    pip install allure-pytest
    pip install faker
    pip install xlrd
    pip install pytest pytest-azurepipelines
    pip install pytest-cov
    pytest --doctest-modules --junitxml=junit/test-results.xml --cov=. --cov-report=xml
    # pytest --alluredir=Allure_Report Tests/
  workingDirectory: $(System.DefaultWorkingDirectory)

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
    testRunTitle: 'Script results'
- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName: 'Report'
    PathToPublish: './TestResults/'
