trigger:
- XYZBank

pool:
  vmImage: 'windows-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'
    addToPath: true

- script: |
    python -m venv env
    source env/bin/activate
    pip install pytest
    pip install selenium
    pip install webdriver_manager
    pip install allure-pytest
    pip install faker
    pip install xlrd
    pip install pytest pytest-azurepipelines
    pip install pytest-cov
    pytest --alluredir=Allure_Report Tests/
  workingDirectory: $(System.DefaultWorkingDirectory)

####
- task: Bash@3
  displayName: 'Generate Allure Report'
  inputs:
    targetType: 'inline'
    script: |
      allure serve $(System.DefaultWorkingDirectory)/Allure_Report
  condition: always()

- task: PublishBuildArtifacts@1
  displayName: 'Publish Allure Report'
  inputs:
    artifactName: 'allure-report'
    pathtoPublish: '$(System.DefaultWorkingDirectory)/allure-report'
####

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: '**/test-*.xml'
    testRunTitle: 'Publish test results for Python $(python.version)'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
    
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
    testRunTitle: 'Script results'

- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName: 'Report'
    PathToPublish: './TestResults/'
- task: AllureGenerate@1
  inputs:
    resultsDir: 'allure-results'
    targetDir: 'allure-report/$(Build.BuildNumber)'
