trigger:
- XYZBank

pool:
  vmImage: 'windows-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'
    addToPath: true

- script: |
    python -m venv env
    source env/bin/activate
    pip install pytest
    pip install selenium
    pytest tests/
  workingDirectory: $(System.DefaultWorkingDirectory)

- task: PublishTestResults@2
  inputs:
    testRunner: XUnit
    testResultsFiles: '**/test-results.xml'
    testRunTitle: 'Test Results'