# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- XYZBank

steps:
- task: BatchScript@1
  inputs:
    filename: 'run_tests.bat'
    arguments: ''
  displayName: 'Run tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: '**/pytest.xml'
    testRunTitle: 'Test Run'
