trigger:
  - XYZBank

pool:
  vmImage: windows-latest
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.10'
        addToPath: true

    - script:
        pytest tests/
      workingDirectory: $(System.DefaultWorkingDirectory)

    - script:
        filename: 'run_tests.bat'
      workingDirectory: $(System.DefaultWorkingDirectory)

    - task: PublishTestResults@2
      inputs:
        testRunner: pytest
        testResultsFiles: '**/test-results.xml'
        testRunTitle: 'Test Results'